if(sessionStorage.getItem("jairampur_admin")!=="1")location.href="login.html";
const defaults={notices:[{date:"03 Sep 2026",title:"Welcome to the new school website",text:"School notices and announcements will be published here.",tag:"General"},{date:"05 Sep 2026",title:"Teachers' Day Celebration",text:"Programme details will be shared by the school office.",tag:"Event"}],events:[{day:"05",month:"SEP",title:"Teachers' Day Celebration",text:"Celebrating our teachers."}],gallery:[["assets/photos/campus.svg","School Campus"]],downloads:[{title:"School Prospectus",meta:"PDF",file:"#"}]};
let d=(()=>{try{return {...defaults,...JSON.parse(localStorage.getItem("jairampur_site_data"))}}catch{return defaults}})();
const $=id=>document.getElementById(id);
function render(){ $("mN").textContent=d.notices.length;$("mE").textContent=d.events.length;$("mG").textContent=d.gallery.length;$("mD").textContent=d.downloads.length;
$("noticesBox").innerHTML=d.notices.map((x,i)=>`<div class="row"><input value="${x.date}" oninput="d.notices[${i}].date=this.value"><input value="${x.title}" oninput="d.notices[${i}].title=this.value"><input value="${x.text}" oninput="d.notices[${i}].text=this.value"><button onclick="d.notices.splice(${i},1);render()">Delete</button></div>`).join("");
$("eventsBox").innerHTML=d.events.map((x,i)=>`<div class="row"><input value="${x.day}" oninput="d.events[${i}].day=this.value"><input value="${x.month}" oninput="d.events[${i}].month=this.value"><input value="${x.title}" oninput="d.events[${i}].title=this.value"><button onclick="d.events.splice(${i},1);render()">Delete</button></div>`).join("");
$("galleryBox").innerHTML=d.gallery.map((x,i)=>`<div class="row galleryrow"><input value="${x[0]}" oninput="d.gallery[${i}][0]=this.value"><input value="${x[1]}" oninput="d.gallery[${i}][1]=this.value"><button onclick="d.gallery.splice(${i},1);render()">Delete</button></div>`).join("");
$("documentsBox").innerHTML=d.downloads.map((x,i)=>`<div class="row"><input value="${x.title}" oninput="d.downloads[${i}].title=this.value"><input value="${x.meta}" oninput="d.downloads[${i}].meta=this.value"><input value="${x.file}" oninput="d.downloads[${i}].file=this.value"><button onclick="d.downloads.splice(${i},1);render()">Delete</button></div>`).join("")}
function addNotice(){d.notices.push({date:"",title:"New notice",text:"",tag:"General"});render()}function addEvent(){d.events.push({day:"01",month:"JAN",title:"New event",text:""});render()}function addGallery(){d.gallery.push(["assets/photos/new-photo.jpg","New gallery item"]);render()}function addDoc(){d.downloads.push({title:"New document",meta:"PDF",file:"documents/new-document.pdf"});render()}function saveAll(){localStorage.setItem("jairampur_site_data",JSON.stringify(d));$("saved").classList.add("show");setTimeout(()=>$("saved").classList.remove("show"),1600)}$("logout").onclick=()=>{sessionStorage.removeItem("jairampur_admin");location.href="login.html"};render();